services:
  db:
    image: "mongo"
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
  backend:
    build: 
      context: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: [
      "poetry", "run", "python", "app/main.py",
    ]
    depends_on:
      - db

volumes:
  mongo-data: